base_model: Qwen/Qwen3-4B-Instruct-2507

sequence_len: 2048
sample_packing: true
load_in_4bit: true

datasets:
  - path: zen_nano_instruct_training_data_fixed_3.jsonl
    type: instruction

num_epochs: 3

adapter: qlora
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05


output_dir: ./zen-nano-finetuned-axolotl


gradient_accumulation_steps: 2
micro_batch_size: 2
learning_rate: 0.0001
optimizer: paged_adamw_8bit


