# Zen-Next Adaptive Compute Configuration
# EXPERIMENTAL - Subject to change

model:
  name: "zen-next-experimental"
  version: "0.1.0-dev"
  base_params: 1_000_000_000  # 1B minimum
  max_params: 13_000_000_000  # 13B maximum

adaptive_compute:
  enabled: true

  # Complexity estimation
  complexity_estimator:
    model_type: "learned"
    features:
      - token_entropy
      - sequence_length
      - vocabulary_diversity
      - syntactic_complexity
      - semantic_density
    update_frequency: 100  # steps
    momentum: 0.9

  # Parameter activation tiers
  activation_tiers:
    minimal:
      params: [1e9, 1.5e9]
      layers: [12, 16]
      hidden_dim: 768
      heads: 12
      threshold: 0.2

    light:
      params: [1.5e9, 3e9]
      layers: [16, 24]
      hidden_dim: 1024
      heads: 16
      threshold: 0.35

    moderate:
      params: [3e9, 6e9]
      layers: [24, 32]
      hidden_dim: 2048
      heads: 32
      threshold: 0.5

    heavy:
      params: [6e9, 9e9]
      layers: [32, 40]
      hidden_dim: 3072
      heads: 48
      threshold: 0.7

    full:
      params: [9e9, 13e9]
      layers: [40, 48]
      hidden_dim: 4096
      heads: 64
      threshold: 0.85

  # Routing configuration
  routing:
    type: "hierarchical"
    granularity: "layer"  # layer, block, or token level
    transition_smoothing: 0.1
    warmup_steps: 1000

  # Dynamic batching
  batching:
    group_by_complexity: true
    max_complexity_difference: 0.15
    reorder_buffer_size: 32
    timeout_ms: 10

memory_consolidation:
  enabled: true

  # Memory types
  short_term:
    capacity: 8192  # tokens
    duration: "1h"
    decay_rate: 0.1

  working:
    capacity: 32768  # tokens
    duration: "24h"
    decay_rate: 0.05
    compression: true

  long_term:
    capacity: "unlimited"
    duration: "persistent"
    consolidation_interval: "24h"
    forgetting_curve: "exponential"
    reinforcement_bonus: 0.15

  # Consolidation process
  consolidation:
    algorithm: "hippocampal_replay"
    replay_frequency: "6h"
    replay_samples: 100
    importance_weighting: true
    surprise_bonus: 0.2

  # Knowledge graph
  knowledge_graph:
    enabled: true
    max_nodes: 100000
    max_edges: 500000
    pruning_threshold: 0.01
    update_method: "incremental"

neural_architecture_search:
  enabled: true

  # Search space
  search_space:
    attention_patterns: ["local", "global", "sparse", "dilated", "butterfly"]
    ffn_variants: ["standard", "gated", "mixture", "switch"]
    layer_types: ["attention", "ffn", "hybrid", "conv", "recurrent"]
    activation_functions: ["gelu", "swish", "relu", "silu", "mish"]

  # Evolution strategy
  evolution:
    population_size: 20
    mutation_rate: 0.1
    crossover_rate: 0.3
    selection_method: "tournament"
    elite_size: 2

  # Gradient-based search
  gradient_search:
    enabled: true
    architecture_lr: 0.001
    weight_decay: 0.0001
    warmup_epochs: 5

  # Constraints
  constraints:
    max_flops: 1e15
    max_memory: 80e9  # 80GB
    max_latency_ms: 200
    min_accuracy: 0.85

bitdelta_integration:
  enabled: true

  # Personalization
  personalization:
    max_deltas_per_user: 1000
    sparsity: 0.001  # 0.1% of parameters
    compression: "int4"
    update_frequency: "daily"

  # Privacy
  privacy:
    differential_privacy: true
    epsilon: 1.0
    delta: 1e-5
    secure_aggregation: true

  # Storage
  storage:
    backend: "sqlite"
    encryption: "aes256"
    max_size_mb: 100
    retention_days: 90

hardware_optimization:
  # GPU allocation
  gpu:
    dynamic_allocation: true
    memory_pool_gb: 80
    kernel_fusion: true
    graph_optimization: true

  # CPU offloading
  cpu:
    offload_threshold: 0.3
    prefetch_distance: 2
    numa_aware: true

  # Quantization
  quantization:
    minimal_mode: "int4"
    light_mode: "int8"
    moderate_mode: "fp16"
    heavy_mode: "bf16"
    full_mode: "fp32"

  # Caching
  cache:
    kv_cache_size_gb: 16
    attention_cache: true
    activation_checkpointing: "selective"

monitoring:
  # Metrics
  metrics:
    track_complexity: true
    track_memory_usage: true
    track_parameter_activation: true
    track_architecture_changes: true

  # Logging
  logging:
    level: "debug"
    file: "zen-next.log"
    rotation: "daily"
    compression: true

  # Telemetry
  telemetry:
    enabled: false  # Disabled for experimental
    endpoint: "https://telemetry.zen-ai.labs"
    batch_size: 100
    flush_interval: 60

experimental_features:
  # Quantum readiness
  quantum_ready:
    enabled: false
    simulator: "qiskit"
    qubit_allocation: 100

  # Neuromorphic
  neuromorphic:
    enabled: false
    spike_coding: true
    event_driven: true

  # Causal reasoning
  causal_reasoning:
    enabled: true
    graph_construction: "learned"
    intervention_testing: true

  # Multimodal extensions
  multimodal:
    enabled: false
    modalities: ["text", "vision", "audio"]
    fusion_method: "cross_attention"

safety:
  # Guardrails
  guardrails:
    complexity_limit: 0.95
    memory_limit_gb: 100
    architecture_stability_threshold: 0.8

  # Fallback
  fallback:
    enabled: true
    fallback_model: "zen-1.5-7b"
    trigger_conditions:
      - "architecture_instability"
      - "memory_overflow"
      - "complexity_overload"

  # Checkpointing
  checkpointing:
    frequency: "hourly"
    keep_last: 24
    compression: "zstd"

# Development settings
development:
  debug_mode: true
  profiling: true
  assertions: true
  test_coverage: true
  benchmark_mode: false